import {
  // Existing Exports
  cuisineTunisiene1,
  cuisineTunisiene2,
  cuisineTunisiene3,
  cuisineTunisiene4,
  cuisineTunisiene5,
  cuisineTunisiene6,
  cuisineTunisiene7,
  cuisineTunisiene8,
  cuisineTunisiene9,
  cuisineTunisiene10,
  cuisineTunisiene11,
  cuisineTunisiene12,
  cuisineTunisiene13,
  PatisserieTunisien_a,
  PatisserieTunisien_b,
  PatisserieTunisien_c,
  PatisserieTunisien_d,
  PatisserieTunisien_e,
  PatisserieTunisien_f,
  PatisserieTunisien_g,
  PatisserieTunisien_h,
  PatisserieTunisien_i,
  PatisserieTunisien_j,
  PatisserieTunisien_k,
  PatisserieTunisien_l,
  PatisserieTunisien_m,
  PatisserieTunisien_n,
  PatisserieTunisien_o,
  PatisserieTunisien_p,
  PatisserieTunisien_q,
  PatisserieTunisien_r,
  PatisserieTunisien_s,
  PatisserieTunisien_t,
  PatisserieTunisien_u,
  PatisserieTunisien_v,
  PatisserieTunisien_w,
  PatisserieTunisien_x,
  PatisserieTunisien_y,
  PatisserieTunisien_z,
  PatisserieTunisien_1,
  PatisserieTunisien_2,
  PatisserieTunisien_3,
  PatisserieTunisien_4,
  PatisserieTunisien_5,
  PatisserieTunisien_6,
  PatisserieTunisien_7,
  PatisserieTunisien_8,
  PatisserieTunisien_9,
  PatisserieTunisien_10,
  PatisserieTunisien_11,
  PatisserieTunisien_12,
  PatisserieTunisien_13,
  PatisserieTunisien_14,
  PatisserieTunisien_15,
  PatisserieTunisien_16,
  PatisserieTunisien_17,
  PatisserieTunisien_18,
  PatisserieTunisien_19,
  PatisserieTunisien_20,
  PatisserieTunisien_21,
  PatisserieTunisien_22,
  PatisserieTunisien_23,
  PatisserieTunisien_24,
  PatisserieTunisien_26,
  PatisserieTunisien_27,
  PatisserieTunisien_28,
  PatisserieTunisien_29,
  PatisserieTunisien_30,
  PatisserieTunisien_31,
  PatisserieTunisien_32,
  PatisserieTunisien_33,
  PatisserieTunisien_34,
  PatisserieTunisien_35,
  PatisserieTunisien_36,
  PatisserieTunisien_37,
  PatisserieTunisien_38,
  PatisserieTunisien_39,
  PatisserieTunisien_40,
  PatisserieTunisien_41,
  PatisserieTunisien_42,
  PatisserieTunisien_43,
  PatisserieTunisien_44,
  PatisserieTunisien_45,
  PatisserieTunisien_46,
  PatisserieTunisien_47,
  PatisserieTunisien_48,
  PatisserieTunisien_49,
  PatisserieTunisien_50,
  chefCooking1,
  chefCooking2,
  chefCooking3,
  elWaeedLogo,
  hero,
  hero1,
  hero2,
  hero3,
  formationA,
  formationB,
  formationC,
  formationD,
  formationE,
  formationF,
  formationG,
  formationH,
  formationI,
  formationJ,
  formationK,
  formationL,
  fruitTarte,
  specialite1,
  specialite2,
  specialite3,
  specialite4,
  specialite5,
  specialite6,
  specialite7,
  specialite8,
  specialite9,
  contactUsImg1,
  contactUsImg2,
  contactUsImg3,
  avatar1,
  avatar2,
  avatar3,
  CuisineTunisienA,
  CuisineTunisienB,
  CuisineTunisienC,
  CuisineTunisienD,
  CuisineTunisienE,
  CuisineTunisienF,
  CuisineTunisienG,
  CuisineTunisienH,
  CuisineTunisienI,
  CuisineTunisienJ,
  CuisineTunisienK,
  CuisineTunisienL,
  CuisineTunisienM,
  PatisserieOriental1,
  PatisserieOriental3,
  PatisserieOriental4,
  PatisserieOriental5,
  PatisserieOriental6,
  PatisserieOriental7,
  PatisserieOriental8,
  PatisserieOriental9,
  PatisserieOriental10,
  PatisserieOriental11,
  PatisserieOriental12,
  PatisserieOriental13,
  PeopleCooking_a,
  PeopleCooking_b,
  PeopleCooking_c,
  PeopleCooking_d,
  PeopleCooking_e,
  PeopleCooking_f,
  PeopleCooking_g,
  PeopleCooking_h,
  PeopleCooking_i,
  PeopleCooking_j,
  PeopleCooking_k,
  PeopleCooking_l,
  PeopleCooking_m,
  PeopleCooking_n,
  PeopleCooking_o,
  PeopleCooking_p,
  PeopleCooking_q,
  PeopleCooking_r,
  PeopleCooking_s,
  PeopleCooking_t,
  PeopleCooking_u,
  PeopleCooking_v,
  PeopleCooking_w,
  PeopleCooking_x,
  PeopleCooking_y,
  PeopleCooking_z,
  PeopleCooking_1,
  PeopleCooking_2,
  PeopleCooking_3,
  PeopleCooking_4,
  AmuseBouche,
  AmuseBouche0,
  AmuseBouche1,
  AmuseBouche2,
  AmuseBouche3,
  AmuseBouche4,
  AmuseBouche5,
  AmuseBouche6,
  AmuseBouche7,
  AmuseBouche8,
  AmuseBouche9,
  AmuseBouche10,
  AmuseBouche11,
  AmuseBouche12,
  AmuseBouche13,
  AmuseBouche14,
  AmuseBouche15,
  AmuseBouche16,
  AmuseBouche17,
  AmuseBouche18,
  AmuseBouche19,
  AmuseBouche20,
  AmuseBouche21,
  Baking1,
  Baking2,
  Baking3,
  Baking4,
  Baking6,
  Baking7,
  Baking8,
  Baking9,
  Baking10,
  Baking11,
  Baking12,
  Baking13,
  Baking14,
  Chocolaterie1,
  Chocolaterie2,
  Chocolaterie3,
  Chocolaterie4,
  Chocolaterie6,
  Chocolaterie7,
  Chocolaterie8,
  Chocolaterie9,
  Chocolaterie10,
  Chocolaterie11,
  Chocolaterie12,
  Chocolaterie13,
  Chocolaterie14,
  Chocolaterie15,
  Chocolaterie16,
  Chocolaterie17,
  Chocolaterie18,
  Chocolaterie19,
  Chocolaterie20,
  Chocolaterie21,
  Chocolaterie23,
  Chocolaterie24,
  Chocolaterie25,
  Chocolaterie26,
  Chocolaterie27,
  Chocolaterie28,
  Chocolaterie29,
  Chocolaterie30,
  Chocolaterie31,
  Chocolaterie32,
  Chocolaterie33,
  Chocolaterie34,
  ChocolaterieA,
  ChocolaterieB,
  ChocolaterieC,
  ChocolaterieD,
  ChocolaterieE,
  ChocolaterieF,
  ChocolaterieG,
  ChocolaterieH,
  ChocolaterieI,
  ChocolaterieJ,
  ChocolaterieK,
  ChocolaterieL,
  ChocolaterieM,
  ChocolaterieN,
  ChocolaterieO,
  ChocolaterieP,
  ChocolaterieQ,
  ChocolaterieR,
  ChocolaterieS,
  ChocolaterieT,
  ChocolaterieU,
  ChocolaterieV,
  ChocolaterieW,
  ChocolaterieX,
  ChocolaterieZ,
  CuisineOrientalB,
  CuisineOrientalC,
  CuisineOrientalD,
  CuisineOrientalE,
  CuisineOrientalF,
  CuisineOrientalG,
  CuisineOrientalH,
  CuisineOrientalI,
  CuisineOrientalJ,
  CuisineOrientalK,
  CuisineOrientalL,
  CuisineOrientalM,
  CuisineOrientalN,
  CuisineOrientalO,
  CuisineOrientalP,
  CuisineOrientalQ,
  CuisineOrientalR,
  EuropeanCookingA,
  EuropeanCookingB,
  EuropeanCookingD,
  EuropeanCookingE,
  EuropeanCookingF,
  EuropeanCookingG,
  EuropeanCookingH,
  EuropeanCookingI,
  EuropeanCookingJ,
  EuropeanCookingK,
  EuropeanCookingL,
  EuropeanPastery1,
  EuropeanPastery2,
  EuropeanPastery3,
  EuropeanPastery4,
  EuropeanPastery5,
  EuropeanPastery7,
  EuropeanPastery8,
  EuropeanPastery9,
  EuropeanPastery10,
  EuropeanPastery11,
  EuropeanPastery12,
  EuropeanPastery13,
  EuropeanPastery14,
  EuropeanPastery15,
  EuropeanPastery16,
  EuropeanPastery17,
  EuropeanPastery18,
  EuropeanPastery19,
  EuropeanPastery20,
  EuropeanPastery21,
  EuropeanPastery22,
  EuropeanPastery24,
  EuropeanPastery25,
  EuropeanPastery26,
  EuropeanPastery27,
  EuropeanPastery28,
  EuropeanPastery29,
  EuropeanPastery30,
  EuropeanPastery31,
  EuropeanPastery32,
  EuropeanPastery33,
  EuropeanPastery34,
  EuropeanPastery35,
  EuropeanPasteryA,
  EuropeanPasteryB,
  EuropeanPasteryD,
  EuropeanPasteryE,
  EuropeanPasteryF,
  EuropeanPasteryG,
  EuropeanPasteryH,
  EuropeanPasteryI,
  EuropeanPasteryJ,
  EuropeanPasteryK,
  EuropeanPasteryL,
  EuropeanPasteryM,
  EuropeanPasteryN,
  EuropeanPasteryO,
  EuropeanPasteryP,
  EuropeanPasteryQ,
  EuropeanPasteryR,
  EuropeanPasteryS,
  EuropeanPasteryT,
  EuropeanPasteryU,
  EuropeanPasteryV,
  EuropeanPasteryW,
  EuropeanPasteryX,
  EuropeanPasteryY,
  EuropeanPasteryZ,
  FastFoodA,
  FastFoodB,
  FastFoodC,
  FastFoodD,
  FastFoodF,
  FastFoodG,
  FastFoodH,
  FastFoodI,
  FastFoodJ,
  FastFoodK,
  FastFoodL,
  FastFoodM,
  KidsCooking1,
  KidsCooking2,
  KidsCooking3,
  KidsCooking4,
  KidsCooking5,
  KidsCooking6,
  KidsCooking7,
  KidsCooking8,
  KidsCooking10,
  KidsCooking11,
  KidsCooking12,
  KidsCooking13,
  KidsCooking16,
  KidsCooking17,
  KidsCookingA,
  KidsCookingB,
  KidsCookingC,
  KidsCookingD,
  KidsCookingE,
  KidsCookingF,
  KidsCookingG,
  KidsCookingH,
  KidsCookingI,
  KidsCookingJ,
  KidsCookingK,
  KidsCookingL,
  KidsCookingM,
  KidsCookingN,
  KidsCookingO,
  KidsCookingP,
  KidsCookingQ,
  KidsCookingR,
  KidsCookingS,
  KidsCookingT,
  KidsCookingU,
  KidsCookingV,
  KidsCookingW,
  KidsCookingX,
  KidsCookingY,
  KidsCookingZ,
  Viennoiserie_b,
  Viennoiserie_c,
  Viennoiserie_d,
  Viennoiserie_e,
  Viennoiserie_f,
  Viennoiserie_g,
  Viennoiserie_h,
  Viennoiserie_i,
  Viennoiserie_j,
  Viennoiserie_k,
} from "../constant/imageData";
export const menuDishesData = [
  {
    imgSrc: formationA,
    dishName: "CuisineT",
    description: "CuisineTD",
    id: "cuisineTunisiene",
    price: "$30",
    rating: 4.7,
    ratingCount: 1125,
    images: [
      cuisineTunisiene1,
      cuisineTunisiene2,
      cuisineTunisiene3,
      cuisineTunisiene4,
      cuisineTunisiene5,
      cuisineTunisiene6,
      cuisineTunisiene7,
      cuisineTunisiene8,
      cuisineTunisiene9,
      cuisineTunisiene10,
      cuisineTunisiene11,
      cuisineTunisiene12,
      cuisineTunisiene13,
      CuisineTunisienA,
      CuisineTunisienB,
      CuisineTunisienC,
      CuisineTunisienD,
      CuisineTunisienE,
      CuisineTunisienF,
      CuisineTunisienG,
      CuisineTunisienH,
      CuisineTunisienI,
      CuisineTunisienJ,
      CuisineTunisienK,
      CuisineTunisienL,
      CuisineTunisienM,
    ],
  },
  {
    imgSrc: formationB,
    dishName: "PatT",
    description: "PatTD",
    id: "patisserieTunisiene",
    price: "$30",
    rating: 4.7,
    ratingCount: 1125,
    images: [
      PatisserieTunisien_a,
      PatisserieTunisien_b,
      PatisserieTunisien_c,
      PatisserieTunisien_d,
      PatisserieTunisien_e,
      PatisserieTunisien_f,
      PatisserieTunisien_g,
      PatisserieTunisien_h,
      PatisserieTunisien_i,
      PatisserieTunisien_j,
      PatisserieTunisien_k,
      PatisserieTunisien_l,
      PatisserieTunisien_m,
      PatisserieTunisien_n,
      PatisserieTunisien_o,
      PatisserieTunisien_p,
      PatisserieTunisien_q,
      PatisserieTunisien_r,
      PatisserieTunisien_s,
      PatisserieTunisien_t,
      PatisserieTunisien_u,
      PatisserieTunisien_v,
      PatisserieTunisien_w,
      PatisserieTunisien_x,
      PatisserieTunisien_y,
      PatisserieTunisien_z,
      PatisserieTunisien_1,
      PatisserieTunisien_2,
      PatisserieTunisien_3,
      PatisserieTunisien_4,
      PatisserieTunisien_5,
      PatisserieTunisien_6,
      PatisserieTunisien_7,
      PatisserieTunisien_8,
      PatisserieTunisien_9,
      PatisserieTunisien_10,
      PatisserieTunisien_11,
      PatisserieTunisien_12,
      PatisserieTunisien_13,
      PatisserieTunisien_14,
      PatisserieTunisien_15,
      PatisserieTunisien_16,
      PatisserieTunisien_17,
      PatisserieTunisien_18,
      PatisserieTunisien_19,
      PatisserieTunisien_20,
      PatisserieTunisien_21,
      PatisserieTunisien_22,
      PatisserieTunisien_23,
      PatisserieTunisien_24,
      PatisserieTunisien_26,
      PatisserieTunisien_27,
      PatisserieTunisien_28,
      PatisserieTunisien_29,
      PatisserieTunisien_30,
      PatisserieTunisien_31,
      PatisserieTunisien_32,
      PatisserieTunisien_33,
      PatisserieTunisien_34,
      PatisserieTunisien_35,
      PatisserieTunisien_36,
      PatisserieTunisien_37,
      PatisserieTunisien_38,
      PatisserieTunisien_39,
      PatisserieTunisien_40,
      PatisserieTunisien_41,
      PatisserieTunisien_42,
      PatisserieTunisien_43,
      PatisserieTunisien_44,
      PatisserieTunisien_45,
      PatisserieTunisien_46,
      PatisserieTunisien_47,
      PatisserieTunisien_48,
      PatisserieTunisien_49,
      PatisserieTunisien_50,
    ],
  },
  {
    imgSrc: formationC,
    dishName: "CuisineO",
    description: "CuisineOD",
    id: "cuisineOriental",
    price: "$39",
    rating: 4.4,
    ratingCount: 2050,
    images: [
      CuisineOrientalB,
      CuisineOrientalC,
      CuisineOrientalD,
      CuisineOrientalE,
      CuisineOrientalF,
      CuisineOrientalG,
      CuisineOrientalH,
      CuisineOrientalI,
      CuisineOrientalJ,
      CuisineOrientalK,
      CuisineOrientalL,
      CuisineOrientalM,
      CuisineOrientalN,
      CuisineOrientalO,
      CuisineOrientalP,
      CuisineOrientalQ,
      CuisineOrientalR,
    ],
  },
  {
    imgSrc: formationL,
    dishName: "Pat",
    description: "PatD",
    id: "patisserieOriental",
    price: "$29",
    rating: 4.3,
    ratingCount: 1080,
    images: [
      PatisserieOriental1,
      PatisserieOriental3,
      PatisserieOriental4,
      PatisserieOriental5,
      PatisserieOriental6,
      PatisserieOriental7,
      PatisserieOriental8,
      PatisserieOriental9,
      PatisserieOriental10,
      PatisserieOriental11,
      PatisserieOriental12,
      PatisserieOriental13,
    ],
  },
  {
    imgSrc: formationD,
    dishName: "CuisineE",
    description: "CuisineED",
    id: "cuisineEuropeene",
    price: "$30",
    rating: 4.7,
    ratingCount: 1125,
    images: [
      EuropeanCookingA,
      EuropeanCookingB,
      EuropeanCookingD,
      EuropeanCookingE,
      EuropeanCookingF,
      EuropeanCookingG,
      EuropeanCookingH,
      EuropeanCookingI,
      EuropeanCookingJ,
      EuropeanCookingK,
      EuropeanCookingL,
    ],
  },
  {
    imgSrc: formationE,
    dishName: "PatE",
    description: "PatED",
    id: "patisserieEuropeene",
    price: "$30",
    rating: 4.7,
    ratingCount: 1125,
    images: [
      EuropeanPastery1,
      EuropeanPastery2,
      EuropeanPastery3,
      EuropeanPastery4,
      EuropeanPastery5,
      EuropeanPastery7,
      EuropeanPastery8,
      EuropeanPastery9,
      EuropeanPastery10,
      EuropeanPastery11,
      EuropeanPastery12,
      EuropeanPastery13,
      EuropeanPastery14,
      EuropeanPastery15,
      EuropeanPastery16,
      EuropeanPastery17,
      EuropeanPastery18,
      EuropeanPastery19,
      EuropeanPastery20,
      EuropeanPastery21,
      EuropeanPastery22,
      EuropeanPastery24,
      EuropeanPastery25,
      EuropeanPastery26,
      EuropeanPastery27,
      EuropeanPastery28,
      EuropeanPastery29,
      EuropeanPastery30,
      EuropeanPastery31,
      EuropeanPastery32,
      EuropeanPastery33,
      EuropeanPastery34,
      EuropeanPastery35,
      EuropeanPasteryA,
      EuropeanPasteryB,
      EuropeanPasteryD,
      EuropeanPasteryE,
      EuropeanPasteryF,
      EuropeanPasteryG,
      EuropeanPasteryH,
      EuropeanPasteryI,
      EuropeanPasteryJ,
      EuropeanPasteryK,
      EuropeanPasteryL,
      EuropeanPasteryM,
      EuropeanPasteryN,
      EuropeanPasteryO,
      EuropeanPasteryP,
      EuropeanPasteryQ,
      EuropeanPasteryR,
      EuropeanPasteryS,
      EuropeanPasteryT,
      EuropeanPasteryU,
      EuropeanPasteryV,
      EuropeanPasteryW,
      EuropeanPasteryX,
      EuropeanPasteryY,
      EuropeanPasteryZ,
    ],
  },
  {
    imgSrc: formationF,
    dishName: "vien",
    description: "vienD",
    id: "Viennoiserie",
    price: "$32",
    rating: 4.6,
    ratingCount: 2120,
    images: [
      Viennoiserie_b,
      Viennoiserie_c,
      Viennoiserie_d,
      Viennoiserie_e,
      Viennoiserie_f,
      Viennoiserie_g,
      Viennoiserie_h,
      Viennoiserie_i,
      Viennoiserie_j,
      Viennoiserie_k,
    ],
  },
  {
    imgSrc: formationG,
    dishName: "Bou",
    description: "BouD",
    id: "boulangerie",
    price: "$24",
    rating: 4.2,
    ratingCount: 1030,
    images: [
      Baking1,
      Baking2,
      Baking3,
      Baking4,
      Baking6,
      Baking7,
      Baking8,
      Baking9,
      Baking10,
      Baking11,
      Baking12,
      Baking13,
      Baking14,
    ],
  },
  {
    imgSrc: formationH,
    dishName: "AmuseBoucheT",
    description: "AmuseBoucheTD",
    id: "amuseBouche",
    price: "$30",
    rating: 4.7,
    ratingCount: 1125,
    images: [
      AmuseBouche,
      AmuseBouche0,
      AmuseBouche1,
      AmuseBouche2,
      AmuseBouche3,
      AmuseBouche4,
      AmuseBouche5,
      AmuseBouche6,
      AmuseBouche7,
      AmuseBouche8,
      AmuseBouche9,
      AmuseBouche10,
      AmuseBouche11,
      AmuseBouche12,
      AmuseBouche13,
      AmuseBouche14,
      AmuseBouche15,
      AmuseBouche16,
      AmuseBouche17,
      AmuseBouche18,
      AmuseBouche19,
      AmuseBouche20,
      AmuseBouche21,
    ],
  },
  {
    imgSrc: formationI,
    dishName: "chou",
    description: "chouD",
    id: "chocolaterie",
    price: "$30",
    rating: 4.7,
    ratingCount: 1125,
    images: [
      Chocolaterie1,
      Chocolaterie2,
      Chocolaterie3,
      Chocolaterie4,
      Chocolaterie6,
      Chocolaterie7,
      Chocolaterie8,
      Chocolaterie9,
      Chocolaterie10,
      Chocolaterie11,
      Chocolaterie12,
      Chocolaterie13,
      Chocolaterie14,
      Chocolaterie15,
      Chocolaterie16,
      Chocolaterie17,
      Chocolaterie18,
      Chocolaterie19,
      Chocolaterie20,
      Chocolaterie21,
      Chocolaterie23,
      Chocolaterie24,
      Chocolaterie25,
      Chocolaterie26,
      Chocolaterie27,
      Chocolaterie28,
      Chocolaterie29,
      Chocolaterie30,
      Chocolaterie31,
      Chocolaterie32,
      Chocolaterie33,
      Chocolaterie34,
      ChocolaterieA,
      ChocolaterieB,
      ChocolaterieC,
      ChocolaterieD,
      ChocolaterieE,
      ChocolaterieF,
      ChocolaterieG,
      ChocolaterieH,
      ChocolaterieI,
      ChocolaterieJ,
      ChocolaterieK,
      ChocolaterieL,
      ChocolaterieM,
      ChocolaterieN,
      ChocolaterieO,
      ChocolaterieP,
      ChocolaterieQ,
      ChocolaterieR,
      ChocolaterieS,
      ChocolaterieT,
      ChocolaterieU,
      ChocolaterieV,
      ChocolaterieW,
      ChocolaterieX,
      ChocolaterieZ,
    ],
  },
  {
    imgSrc: formationJ,
    dishName: "Fastf",
    description: "FastfD",
    id: "fastFood",
    price: "$19",
    rating: 4.1,
    ratingCount: 999,
    images: [
      FastFoodA,
      FastFoodB,
      FastFoodC,
      FastFoodD,
      FastFoodF,
      FastFoodG,
      FastFoodH,
      FastFoodI,
      FastFoodJ,
      FastFoodK,
      FastFoodL,
      FastFoodM,
    ],
  },
  {
    imgSrc: formationK,
    dishName: "KidCookingT",
    description: "KidCookingTD",
    id: "kidsCooking",
    price: "$30",
    rating: 4.7,
    ratingCount: 1125,
    images: [
      KidsCooking1,
      KidsCooking2,
      KidsCooking3,
      KidsCooking4,
      KidsCooking5,
      KidsCooking6,
      KidsCooking7,
      KidsCooking8,
      KidsCooking10,
      KidsCooking11,
      KidsCooking12,
      KidsCooking13,
      KidsCooking16,
      KidsCooking17,
      KidsCookingA,
      KidsCookingB,
      KidsCookingC,
      KidsCookingD,
      KidsCookingE,
      KidsCookingF,
      KidsCookingG,
      KidsCookingH,
      KidsCookingI,
      KidsCookingJ,
      KidsCookingK,
      KidsCookingL,
      KidsCookingM,
      KidsCookingN,
      KidsCookingO,
      KidsCookingP,
      KidsCookingQ,
      KidsCookingR,
      KidsCookingS,
      KidsCookingT,
      KidsCookingU,
      KidsCookingV,
      KidsCookingW,
      KidsCookingX,
      KidsCookingY,
      KidsCookingZ,
    ],
  },
];
export const ourSpecialitiesList = [
  {
    image: specialite1,
    name: "nuddles",
  },
  {
    image: specialite2,
    name: "burger",
  },
  {
    image: specialite3,
    name: "salad",
  },
  {
    image: specialite4,
    name: "bread dish",
  },
  {
    image: specialite5,
    name: "pasta",
  },
  {
    image: specialite6,
    name: "sandwich",
  },
];

export const socialLinksMap = [
  {
    socialLink: "https://www.facebook.com/",
    /*socialIconName: icons.facebookIcon,*/
  },
  {
    socialLink: "https://www.youtube.com/",
    /* socialIconName: icons.youtubeIcon,*/
  },

  {
    socialLink: "https://www.instagram.com/",
    /*socialIconName: icons.instagramIcon,*/
  },
];

export const restaurantTimeMap = [
  {
    restaurantWeek: "dayA",
    restaurantTime: "timeA",
  },
  {
    restaurantWeek: "dayB",
    restaurantTime: "timeB",
  },
  {
    restaurantWeek: "dayC",
    restaurantTime: "timeC",
  },
];

export const drinkNamesData = [
  {
    drinkName: "Mocktail",
    drinkVariant: "Blueberry / Pineapple Mint Refreshed / Margarita ",
    price: "$13",
  },
  {
    drinkName: "Fruit Shakes",
    drinkVariant: "Apple / Mango / Watermelon / Banana / Strawberry.",
    price: "$18",
  },
  {
    drinkName: "Alcohol",
    drinkVariant: "Ember Whiskey / Crimson Tide Vodka / Horizon Rum",
    price: "$15",
  },
  {
    drinkName: "Soda",
    drinkVariant: "Cherry Wave /Berry Blast Soda / Mango Breeze Soda",
    price: "$10",
  },
];

export const dessertsNamesData = [
  {
    dessertName: "Cakes",
    dessertVariant:
      "Velvet Dream Cake / Chocolate Decadence / Strawberry Cake ",
    price: "$8",
  },
  {
    dessertName: "Muffins",
    dessertVariant: "Mocha Magic Muffins / Choco-Chip  / Banana Nut Crunch ",
    price: "$10",
  },
  {
    dessertName: "Donets",
    dessertVariant:
      "Blueberry Burst / Coconut Paradise  / Caramel Crunch Rings.",
    price: "$15",
  },
  {
    dessertName: "Ice Cream",
    dessertVariant: "Vanilla Bean Bliss /Coconut Almond Joy / Butter Scooch",
    price: "$8",
  },
];

export const reviewsSwiperData = [
  {
    reviewMessage: "avatarBend1",
    imgSrc: avatar3,
    name: "Dhouha Meddeb",
  },
  {
    reviewMessage: "avatarBend2",
    imgSrc: avatar2,
    name: "Hedi Atrous",
  },
];
